name: build

on:
  workflow_dispatch:
  push:
    branches: master
  schedule:
    # Run Hourly
    - cron:  '0 1 * * *'
  

jobs:
        
  cosmos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: cosmos/Dockerfile
          context: cosmos
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/notional-labs/cosmos:latest
          
          
  evmos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: evmos/Dockerfile
          context: evmos
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/notional-labs/images/evmos:latest


  gaia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: gaia/Dockerfile
          context: gaia
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/notional-labs/images/gaia:latest


  osmosis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: osmosis/Dockerfile
          context: osmosis
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/notional-labs/images/osmosis:latest



  gno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: osmosis/Dockerfile
          context: gno
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/notional-labs/images/gno:latest



  juno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: juno/Dockerfile
          context: juno
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/notional-labs/images/juno:latest
